"""
Kanban Automation Plugin for JudeCode.

Auto-creates Kanban boards, tracks progress, manages checkpoints.
ใช้ทุกครั้งที่เริ่มงานใหม่!

=== Vault Path ===
Uses the SAME vault path as the Knowledge Vault system.
Respects JUDECODE_VAULT environment variable.
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Optional

# ─── Shared Vault Path (respects JUDECODE_VAULT) ───
# Same logic as knowledge/vault.py - but we avoid importing from there
# to keep this plugin self-contained (it can be run standalone)
_DEFAULT_VAULT = os.path.expanduser("~/.judecode/vault")
VAULT_PATH = Path(os.environ.get("JUDECODE_VAULT", _DEFAULT_VAULT))
VAULT_PATH.mkdir(parents=True, exist_ok=True)


def slugify(title: str) -> str:
    """Convert title to safe filename."""
    import re
    s = re.sub(r"[^\w\s-]", "", title).strip().lower()
    s = re.sub(r"[-\s]+", "-", s)
    return s or "untitled"


# ─── Kanban Board Generator ───

def create_kanban(
    title: str,
    backlog: list[str],
    todo: list[str],
    context: str = "",
    tags: Optional[list[str]] = None,
) -> str:
    """
    Create a new Kanban board note in the vault.
    
    Args:
        title: Project/task name
        backlog: List of backlog items (สิ่งที่ต้องทำ)
        todo: List of items for this round (เลือกมาทำรอบนี้)
        context: Additional context/notes
        tags: Optional list of tags
    
    Returns:
        The filename of the created note
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    filename = f"kanban-{slugify(title)}"
    tags_str = "[" + ", ".join(f"'{t}'" for t in (tags or ["kanban"])) + "]"
    
    # Build backlog items
    backlog_items = "\n".join(f"- [ ] {item}" for item in backlog)
    todo_items = "\n".join(f"- [ ] {item}" for item in todo)
    
    content = f"""---
title: "Kanban: {title}"
created: {now}
tags: {tags_str}
links: ['session-context-active', 'checkpoint-resume-log']
---

# 🎯 Kanban: {title}

**Created:** {now}
**Status:** 🟢 Active

---

## 📥 Backlog
{backlog_items if backlog_items else "- (empty)"}

## 📋 To Do (รอบนี้)
{todo_items if todo_items else "- (empty)"}

## ⚡ In Progress
- (none yet)

## ✅ Done
- (none yet)

## 🔍 Notes
{context}

---

## 📊 Progress
- **Total Tasks:** {len(backlog) + len(todo)}
- **Done:** 0
- **In Progress:** 0
- **Remaining:** {len(backlog) + len(todo)}

---
*Auto-generated by JudeCode Kanban Plugin*
"""
    
    filepath = VAULT_PATH / f"{filename}.md"
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"✅ Kanban created: {filename}")
    return filename


# ─── Session Context Manager ───

def update_session_context(
    goal: str,
    original_request: str,
    progress: list[dict],
    key_decisions: list[str] = None,
    files_modified: list[str] = None,
    remaining_tasks: list[str] = None,
    next_action: str = "",
    status: str = "🟢 Active",
):
    """
    Update the session-context-active note.
    
    Args:
        goal: Main goal of the session
        original_request: Original user request text
        progress: List of dicts with keys: task, status, notes
        key_decisions: List of important decisions made
        files_modified: List of files changed
        remaining_tasks: List of remaining tasks
        next_action: What to do next
        status: 🟢 Active / 🟡 Paused / 🔴 Error / ✅ Complete
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Build progress table
    progress_rows = ""
    for i, item in enumerate(progress, 1):
        progress_rows += f"| {i} | {item.get('task', '')} | {item.get('status', '📋')} | {item.get('notes', '')} |\n"
    
    decisions_text = "\n".join(f"- {d}" for d in (key_decisions or []))
    files_text = "\n".join(f"- `{f}`" for f in (files_modified or []))
    remaining_text = "\n".join(f"- [ ] {t}" for t in (remaining_tasks or []))
    
    content = f"""---
title: "Session Context (Active)"
updated: {now}
status: {status}
---

# 🧠 Session Context (Active)

> **อัปเดตล่าสุด:** {now}  
> **สถานะ:** {status}

---

## 📌 เป้าหมายหลัก (Main Goal)
```
{goal}
```

---

## 📋 Progress Summary
| # | Task | Status | Notes |
|---|------|--------|-------|
{progress_rows}

---

## 🔄 Original Request (คำขอเดิม)
```
{original_request}
```

## 💡 Key Decisions
{decisions_text if decisions_text else "- (ไม่มี)"}

## 📂 Files Modified
{files_text if files_text else "- (ยังไม่มี)"}

## 📋 Remaining Tasks
{remaining_text if remaining_text else "- (ไม่มี)"}

## ➡️ Next Action
> {next_action if next_action else "รอคำสั่งถัดไป"}
"""
    
    filepath = VAULT_PATH / "session-context-active.md"
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"✅ Session context updated: {status}")


# ─── Checkpoint Manager ───

def save_checkpoint(
    step_name: str,
    action: str,
    status: str = "✅",
    notes: str = "",
    continuation_count: int = 0,
):
    """
    Save a checkpoint to the resume log.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    filepath = VAULT_PATH / "checkpoint-resume-log.md"
    
    if not filepath.exists():
        # Create initial log
        content = f"""---
title: "Checkpoint & Resume Log"
updated: {now}
---

# 🔄 Checkpoint & Resume Log

## 📝 Checkpoints
| # | Timestamp | Step | Status | Notes |
|---|-----------|------|--------|-------|
| 1 | {now} | {step_name} | {status} | {notes} |

## 🛟 Emergency Resume
```yaml
session_id: ""
last_completed: "{step_name}"
next_action: "{action}"
continuation_count: {continuation_count}
```
"""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
    else:
        # Append checkpoint
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        
        # Find last checkpoint number
        import re
        nums = re.findall(r"^\| (\d+) \|", content, re.MULTILINE)
        next_num = max(int(n) for n in nums) + 1 if nums else 1
        
        # Insert before Emergency Resume section
        checkpoint_line = f"| {next_num} | {now} | {step_name} | {status} | {notes} |\n"
        
        # Update emergency resume yaml
        yaml_block = f"""```yaml
session_id: ""
last_completed: "{step_name}"
next_action: "{action}"
continuation_count: {continuation_count}
```"""
        
        # Simple approach: append to the log table
        if "## 📝 Checkpoints" in content:
            # Find the checkpoint table end
            lines = content.split("\n")
            new_lines = []
            in_table = False
            table_ended = False
            for line in lines:
                if line.startswith("## 📝 Checkpoints"):
                    in_table = True
                    new_lines.append(line)
                    continue
                if in_table and line.startswith("|") and not line.strip().endswith("|---"):
                    # Still in table
                    new_lines.append(line)
                    continue
                if in_table and not line.startswith("|"):
                    # Table ended, insert our new row
                    new_lines.append(checkpoint_line)
                    in_table = False
                    table_ended = True
                
                if table_ended and "last_completed" in line:
                    new_lines.append(f'last_completed: "{step_name}"')
                    continue
                if table_ended and "next_action" in line:
                    new_lines.append(f'next_action: "{action}"')
                    continue
                if table_ended and "continuation_count" in line:
                    new_lines.append(f"continuation_count: {continuation_count}")
                    continue
                
                new_lines.append(line)
            
            content = "\n".join(new_lines)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
    
    print(f"✅ Checkpoint saved: {step_name} ({status})")


# ─── Resume Reader ───

def read_checkpoint() -> Optional[dict]:
    """
    Read the latest checkpoint for resume.
    Returns dict with resume info or None if no checkpoint exists.
    """
    filepath = VAULT_PATH / "checkpoint-resume-log.md"
    if not filepath.exists():
        return None
    
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Parse yaml block
    import re
    yaml_match = re.search(r"```yaml\n(.*?)```", content, re.DOTALL)
    if not yaml_match:
        return None
    
    yaml_text = yaml_match.group(1)
    result = {}
    for line in yaml_text.strip().split("\n"):
        if ":" in line:
            key, _, value = line.partition(":")
            result[key.strip()] = value.strip().strip('"')
    
    return result


# ─── Quick Board Status ───

def get_kanban_status(title: str) -> Optional[dict]:
    """Get the current status of a kanban board."""
    filename = f"kanban-{slugify(title)}.md"
    filepath = VAULT_PATH / filename
    if not filepath.exists():
        return None
    
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Simple parsing
    sections = {}
    current_section = None
    items = []
    
    for line in content.split("\n"):
        if line.startswith("## "):
            if current_section and items:
                sections[current_section] = items
            current_section = line.replace("## ", "").strip()
            items = []
        elif line.strip().startswith("- [") and current_section:
            items.append(line.strip())
    
    if current_section and items:
        sections[current_section] = items
    
    return sections


# ─── Task Card Mover ───

def move_card(title: str, task: str, from_col: str, to_col: str):
    """
    Move a task card between kanban columns.
    
    Args:
        title: Kanban board title
        task: Task text to move
        from_col: Source column name
        to_col: Target column name
    """
    filename = f"kanban-{slugify(title)}.md"
    filepath = VAULT_PATH / filename
    if not filepath.exists():
        print(f"❌ Kanban '{title}' not found")
        return
    
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Find and move the task
    lines = content.split("\n")
    new_lines = []
    current_section = None
    moved = False
    
    for line in lines:
        if line.startswith("## "):
            current_section = line.replace("## ", "").strip()
        
        if current_section == from_col and task in line and not moved:
            # Skip this line (remove from source)
            moved = True
            continue
        
        new_lines.append(line)
    
    if moved:
        # Add to target column
        # Find the target section
        target_idx = -1
        for i, line in enumerate(new_lines):
            if line.startswith("## ") and line.replace("## ", "").strip() == to_col:
                target_idx = i
                break
        
        if target_idx >= 0:
            # Find the right insertion point
            insert_at = target_idx + 1
            for i in range(target_idx + 1, len(new_lines)):
                if new_lines[i].startswith("## ") or i == len(new_lines) - 1:
                    insert_at = i
                    break
            
            # Toggle checkbox based on target column
            checked = " [x]" if to_col == "✅ Done" else " [ ]"
            task_marked = task.replace("[ ]", checked)
            new_lines.insert(insert_at, task_marked)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(new_lines))
    
    print(f"✅ Card moved: '{task}' → {to_col}")


# ─── CLI Helper (for testing) ───

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python kanban_automation.py <command> [args...]")
        print("Commands: create, move, status, checkpoint, resume")
        sys.exit(1)
    
    cmd = sys.argv[1]
    
    if cmd == "create":
        title = sys.argv[2] if len(sys.argv) > 2 else "Test Project"
        backlog = ["Research", "Design", "Implement"]
        todo = ["Setup environment"]
        create_kanban(title, backlog, todo, tags=["test"])
    
    elif cmd == "status":
        title = sys.argv[2] if len(sys.argv) > 2 else "Test Project"
        status = get_kanban_status(title)
        if status:
            print(json.dumps(status, indent=2, ensure_ascii=False))
        else:
            print(f"❌ Kanban '{title}' not found")
    
    elif cmd == "checkpoint":
        step = sys.argv[2] if len(sys.argv) > 2 else "Test step"
        save_checkpoint(step, "Continue working")
    
    elif cmd == "resume":
        cp = read_checkpoint()
        if cp:
            print(json.dumps(cp, indent=2, ensure_ascii=False))
        else:
            print("❌ No checkpoint found")
